# Generated by Django 4.2.1 on 2023-05-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_subtype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subtype_category',
            field=models.IntegerField(choices=[(0, 'Жилая'), (1, 'Загородная'), (2, 'Коммерческая')], default=0),
        ),
    ]
