# Generated by Django 4.2.1 on 2023-05-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_area_remove_realestate_metro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area_abbr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
