# Generated by Django 4.2.1 on 2023-05-27 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_area_area_abbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realestate',
            name='max_floor',
            field=models.CharField(default=6, max_length=4),
            preserve_default=False,
        ),
    ]
