# Generated by Django 4.2.1 on 2023-05-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_realestate_area_realestate_max_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='price',
            field=models.IntegerField(),
        ),
    ]
