# Generated by Django 4.2.1 on 2023-05-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_realestate_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='price',
            field=models.IntegerField(),
        ),
    ]
