# Generated by Django 4.2.1 on 2023-05-27 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_realestate_date_create_realestate_date_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='real_estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='main.realestate'),
        ),
    ]
