# Generated by Django 4.2.1 on 2023-05-29 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_owner_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_request', models.DateTimeField(auto_now_add=True)),
                ('request_status', models.CharField(max_length=50)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.buyer')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.discount')),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.realestate')),
                ('realtor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.realtor')),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
