# Generated by Django 4.2.1 on 2023-05-29 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_request_real_estate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='real_estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.realestate'),
        ),
    ]
