# Generated by Django 4.2.1 on 2023-05-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_image_real_estate'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtor',
            name='realtor_image',
            field=models.ImageField(blank=True, upload_to='realtor_photo/%Y/%m/%d/', verbose_name='Фото риелтора'),
        ),
    ]
